<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept all cookies</name>
   <tag></tag>
   <elementGuidId>9b622a5f-f6b0-438d-9e8c-331a6fe25526</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.cp_accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='cp']/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08f29850-cc2e-4335-a668-60d65667e6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cp_accept</value>
      <webElementGuid>d7704093-a94f-4614-af6f-86b1147e1199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept all cookies</value>
      <webElementGuid>881b2b9f-ae04-48ae-844e-0aba5ac819d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cp&quot;)/div[@class=&quot;grid-row cp_large&quot;]/div[@class=&quot;grid-col-3 cp_link&quot;]/button[@class=&quot;cp_accept&quot;]</value>
      <webElementGuid>9eb7f618-91f8-4f5b-bc66-4928e4467253</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cp']/div/div[2]/button</value>
      <webElementGuid>d7fd848a-a460-4871-81c7-e6b0a1c8a899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='privacy policy'])[1]/following::button[1]</value>
      <webElementGuid>6f844dfe-afdf-4158-a621-32e0b74802ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cookies'])[1]/following::button[1]</value>
      <webElementGuid>22d7584a-1442-43f9-a402-6dd80dcc926e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline all cookies'])[1]/preceding::button[1]</value>
      <webElementGuid>92df714b-9880-4a35-9cdc-a3468f707ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize'])[1]/preceding::button[2]</value>
      <webElementGuid>9a996b89-c693-4a3d-a148-df38a8a54fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept all cookies']/parent::*</value>
      <webElementGuid>7748e88b-54b9-44e6-b1d2-d76f3328744a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>bcd7b507-041b-4d1a-987f-f7918f317e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Accept all cookies' or . = 'Accept all cookies')]</value>
      <webElementGuid>a39d90a4-4082-4ca5-8b81-246b0b591ae8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
