<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>3f15d36d-2f88-4ef5-b97f-596552584ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20ad50b8-76aa-40e2-a5ce-4951e20ab6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dm js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;default_content page_content wpb-js-composer ishover ischrome isnotie&quot;]/div[6]/div[1]</value>
      <webElementGuid>07599c9c-49f7-43eb-9bbb-b7a7e8d5a212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>a570be5b-a376-4b75-bb7f-cb28f2169a1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
