<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_CAPTCHA_a-rrwbc7vtgs8n</name>
   <tag></tag>
   <elementGuidId>85b7d373-9cb6-4d3a-b70e-1bc54ff9f172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-rrwbc7vtgs8n&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-rrwbc7vtgs8n']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2fe4362b-4035-4483-a690-bab90e1f466c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>d168a834-982d-402c-9e7f-23371147272b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcGryITAAAAAOyfLQ7l9FxydHV08PmVIrhD5aED&amp;co=aHR0cHM6Ly9hdG9zLm5ldDo0NDM.&amp;hl=en&amp;v=Y-cOIEkAqcfDdup_qnnmkxIC&amp;theme=light&amp;size=normal&amp;cb=ojr3z2fwkpb3</value>
      <webElementGuid>eca8c31b-00f8-4d0b-8aa4-65dc5d688895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>ba4a791f-43a1-486d-ad5b-00548ad94c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>0bdd4e62-3284-4d04-b36c-eb933be73426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>9c00d897-9283-4f38-a81c-b0d3d517e24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-rrwbc7vtgs8n</value>
      <webElementGuid>9b936d65-3d93-4e1f-b324-6f8636f47e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c3ea49d1-f9de-450f-a568-8c64e9080a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>294b33e0-2c6b-41c0-8e7a-6cd12973a84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>ce2f5368-18f0-41c6-89d8-c248875149a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1011</value>
      <webElementGuid>b53f0d69-1f42-4e08-b845-93b6d903ba11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_171_6&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>e71f2e58-ba21-433d-8543-1eead44ff3f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-rrwbc7vtgs8n']</value>
      <webElementGuid>41ee8a14-c51b-4b6c-915f-91a9e30af570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input_171_6']/div/div/iframe</value>
      <webElementGuid>1d2610ad-1852-4f6b-ad43-855ef8b043c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7f672eaf-4cb3-4bb3-a0ec-410132940824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcGryITAAAAAOyfLQ7l9FxydHV08PmVIrhD5aED&amp;co=aHR0cHM6Ly9hdG9zLm5ldDo0NDM.&amp;hl=en&amp;v=Y-cOIEkAqcfDdup_qnnmkxIC&amp;theme=light&amp;size=normal&amp;cb=ojr3z2fwkpb3' and @name = 'a-rrwbc7vtgs8n']</value>
      <webElementGuid>1f238095-df21-4294-8bd7-a58451eb0cc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
