<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_1</name>
   <tag></tag>
   <elementGuidId>bcd99c84-841f-4578-b109-934d56c4191a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_171_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_171_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f053447a-82fd-486d-9dd4-7f3169bceb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_1</value>
      <webElementGuid>855c681c-44ef-4a4a-933a-e8c31946bf5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_171_1</value>
      <webElementGuid>43d337bd-9c74-4791-9083-998e6197fc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eff228b8-f780-4883-bf8b-1f6ba2d09ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>31274a97-2f95-4f42-9f82-c6eaa62e8fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8723232d-69f7-4ae2-9a91-468493b8fc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1002</value>
      <webElementGuid>f5636eb8-34cf-405e-9fd2-6aa4b63e6408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>28f61597-42e1-4aca-a971-29ed250fd926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>26b3833f-ac6c-4ee7-93f3-102769789823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_171_1&quot;)</value>
      <webElementGuid>f927799b-3c45-4e20-8554-9d3a0cab327a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_171_1']</value>
      <webElementGuid>faf24b08-d254-41ba-a866-768e715deaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='field_171_1']/div/input</value>
      <webElementGuid>5ad198a3-7ba4-47de-bdfa-7536efaa9922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/input</value>
      <webElementGuid>dc1408b0-1b64-437d-b332-c7543102d74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_1' and @id = 'input_171_1' and @type = 'text']</value>
      <webElementGuid>5b489c66-5bfe-4e6f-b024-d8ce2a1d113f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
