<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_4</name>
   <tag></tag>
   <elementGuidId>43958bf3-db37-4fc3-a92c-974af09fe38a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_171_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_171_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8301f74-f766-4d31-81f6-f8cb527a893b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_4</value>
      <webElementGuid>cb76f3e9-6aeb-4883-b424-46048deca3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_171_4</value>
      <webElementGuid>6e94a153-3f9b-4488-92a4-58727551cd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8409cb11-61c6-4b77-b467-daee75971fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>285f0790-ae8e-4d0f-91ae-7a5dbd9424b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1004</value>
      <webElementGuid>6eebbca0-549b-4685-85e3-d2bff8c1bba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce69fd79-91e3-4ec0-bf70-0062bb1654a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c202d32-1ae2-4095-91df-b8cff82c9502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_171_4&quot;)</value>
      <webElementGuid>5982a7c4-cd8d-47ca-9005-1ac5dd84bdae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_171_4']</value>
      <webElementGuid>9f823205-c2c1-4715-b3d8-dead5bd0e600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='field_171_4']/div/input</value>
      <webElementGuid>b7d08b05-8ec4-4543-bb54-85f0ae8b2d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/input</value>
      <webElementGuid>67eb852d-54ef-4580-895c-f76f02856fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_4' and @id = 'input_171_4' and @type = 'email']</value>
      <webElementGuid>fec4228b-59b2-4368-bfe4-b1de48a149d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
