<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_privacy policy_input_24.1</name>
   <tag></tag>
   <elementGuidId>94946e7d-01c7-4101-9514-2dda012d3995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choice_171_24_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='choice_171_24_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebfb11ee-6d73-4c56-a655-c6ffb1517da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gfield-choice-input</value>
      <webElementGuid>23757899-f5fa-4a7a-850c-bb98c1fe490c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_24.1</value>
      <webElementGuid>11b28e53-b4b2-411a-b2b3-48a303e8004f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>edde6195-9d60-4c1b-9ce3-d8310e06d27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>e5739010-61aa-4cb3-ad19-31d53e93fb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choice_171_24_1</value>
      <webElementGuid>ef92d121-c5bf-49e1-bb9a-f0bcf2461c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1010</value>
      <webElementGuid>615a8a7b-0b52-4b2d-b1e8-4031e5156628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choice_171_24_1&quot;)</value>
      <webElementGuid>feb1e867-22b5-40af-91b4-00ab1b79477c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='choice_171_24_1']</value>
      <webElementGuid>69a54086-df48-4cb0-b096-1fec03b6998c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='input_171_24']/li/input</value>
      <webElementGuid>9c418d11-3f4e-4989-be58-3a2a773a7511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/div/ul/li/input</value>
      <webElementGuid>2c0e58c0-20be-40ca-a758-5fdea8944186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_24.1' and @type = 'checkbox' and @id = 'choice_171_24_1']</value>
      <webElementGuid>26e69244-b4a4-43c1-be8c-385bac1ca8cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
