<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_10</name>
   <tag></tag>
   <elementGuidId>7420a153-4de3-499e-8ff8-12ed4b1ba6f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_171_10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_171_10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00ee34c1-cd29-4817-977a-68b769fddf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_10</value>
      <webElementGuid>0d48a30a-3959-4eb2-8a13-202bdff6847c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_171_10</value>
      <webElementGuid>acba232d-b722-4fad-9c4a-117519258de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7661229d-de40-4182-b8fb-87573355b90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>faa1f399-51d6-43a8-b1b5-20093067ffcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>ec073010-ad3f-42fa-812d-5b013acb7120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1003</value>
      <webElementGuid>33726d31-1378-464c-aa95-8dbcb8600336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>937108bb-5030-4ed1-a8d8-1aaf2a3fd707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ffa6841-e7be-45cb-ac26-15946cbbcd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_171_10&quot;)</value>
      <webElementGuid>4a635456-0af8-4013-8201-be999305928f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_171_10']</value>
      <webElementGuid>d257e8bc-3d30-4f5e-add9-616db5b4a130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='field_171_10']/div/input</value>
      <webElementGuid>e7e512de-1879-474e-9591-41bab27a0d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/input</value>
      <webElementGuid>1d86894a-095c-4ffd-84ae-277105d50756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_10' and @id = 'input_171_10' and @type = 'text']</value>
      <webElementGuid>e434f1dc-6f0d-48ee-9cc2-c4fbec179378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
