<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_7.1</name>
   <tag></tag>
   <elementGuidId>ec6ad1f6-64f5-4b0b-959b-c58f433f8ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choice_171_7_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='choice_171_7_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7348bbef-910e-4376-a4bf-7d88a39c6df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gfield-choice-input</value>
      <webElementGuid>009acc2f-5848-4fe0-99be-f2039bec6125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_7.1</value>
      <webElementGuid>9a31eee8-8312-407d-84bf-6bc1cb369506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>64f73c5d-bf47-4087-a275-593ad40da3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>664ec8fd-9cfc-4ea1-b1a6-ac63fa44e7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choice_171_7_1</value>
      <webElementGuid>99ad22fa-9d59-453f-ba62-58f4294daf7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1009</value>
      <webElementGuid>e403fe32-fb86-4eec-b10c-a697e60317dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choice_171_7_1&quot;)</value>
      <webElementGuid>84e3747c-a87a-4d35-bbf1-3cb7c4939565</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='choice_171_7_1']</value>
      <webElementGuid>2a5f74f5-c345-4552-8d86-50191dd3427f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='input_171_7']/li/input</value>
      <webElementGuid>7f728758-9893-4276-b063-52f416564ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>ef084cee-fd06-46aa-8a0e-028687af2f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_7.1' and @type = 'checkbox' and @id = 'choice_171_7_1']</value>
      <webElementGuid>21a3d76d-29dd-4a13-966f-e7ebc92fb4a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
