<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please selectNew Solution or Service_1d78fe</name>
   <tag></tag>
   <elementGuidId>5229187c-5a06-46b7-b92b-559c491857e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_171_26</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input_171_26']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b4dc4991-f401-49e7-8ac8-53573f923c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_26</value>
      <webElementGuid>17d693f1-957e-4ab6-afb7-5f5d67e8360b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_171_26</value>
      <webElementGuid>94aa07a9-a4e8-4de7-affa-bfc3a0e99bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medium gfield_select</value>
      <webElementGuid>e634bbd6-c805-47eb-9dc7-171bc086bded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>84d5e351-8336-4916-84ed-e23f52464d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34aa96d8-53c5-44b0-acae-7526662bea50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cf2c5a99-1cb6-4d2a-9572-f2dc1c243c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectNew Solution or Services for Your BusinessProduct/Customer Support (current Atos clients only)Accounting, Billing or PaymentsJob InformationPress InquirySelling to AtosAlliance/Partnership MattersReport security issue (Atos CERT)Other</value>
      <webElementGuid>1a0a458b-ccde-440c-a00a-96765bbc0b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_171_26&quot;)</value>
      <webElementGuid>b1a2afe7-70ad-4b7b-bc8a-14871d906bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input_171_26']</value>
      <webElementGuid>7b8efcdc-4030-4ce0-94de-dae0e0fa4473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='field_171_26']/div/select</value>
      <webElementGuid>f5beb394-6d81-4486-ba8e-173cb984660f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>190f83ee-f3f6-4c1e-a5ee-0706d3b1a5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>175d1ae1-7c8d-45bb-924f-19912d0cb613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1661816e-05d6-4f4e-b5a1-b52a940a20c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'input_26' and @id = 'input_171_26' and (text() = 'Please selectNew Solution or Services for Your BusinessProduct/Customer Support (current Atos clients only)Accounting, Billing or PaymentsJob InformationPress InquirySelling to AtosAlliance/Partnership MattersReport security issue (Atos CERT)Other' or . = 'Please selectNew Solution or Services for Your BusinessProduct/Customer Support (current Atos clients only)Accounting, Billing or PaymentsJob InformationPress InquirySelling to AtosAlliance/Partnership MattersReport security issue (Atos CERT)Other')]</value>
      <webElementGuid>ef76a37d-63a9-4caf-b9a1-49de3154a6fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
